UninstallTask uses ConnectedDeviceProvider.
It used to call adb directly.

This has the side effect of allowing ANDROID_SERIAL filtering for
uninstalls, and uninstalling from all connected devices if there are
more than one, rather than looping on:
    - waiting for device -
    error: more than one device and emulator

Install & Uninstall infomation is logged at the LIFECYCLE level, so it
is visible by default. The final "(un)installed from n devices" is
logged at QUIET level, so will be seen even with -q.

Change-Id: I46100c0000a6507c4d35bd009849f5aa789afc9e